version: '3'
services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/postgres
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=password
      - SPRING_LIQUIBASE_CHANGELOG=classpath:db/changelog/db.changelog-master.yaml
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_LIQUIBASE_USER=user
      - SPRING_LIQUIBASE_PASSWORD=password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge