server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: user
    password: password