name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run_tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build
        run: |
          ./gradlew build --no-daemon
          EXIT_CODE=$?
          if [[ $EXIT_CODE -ne 0 ]]; then
            echo "Build failed. Aborting the push."
            exit $EXIT_CODE
          fi

      - name: Run Tests
        run: |
          ./gradlew test --no-daemon
          EXIT_CODE=$?
          if [[ $EXIT_CODE -ne 0 ]]; then
            echo "Tests failed. Aborting the push."
            exit $EXIT_CODE
          fi